### ISSUE TITLE
Interfacing the Transceiver

### ISSUE THREAD

**Issue by mikeshams** [gurman1995/capstone-project-embt-2020#5]
Abdul - 1) What issues did you face when Interfacing the transceiver to the Arduino and the BBB? 2) how did you resolve them?

**Comment by muqeeth54** [comment]
Initially, when I was using the RF module, I had a data loss at the 9600 Baud rate.  And then when I analyzed the issue on the internet, I understood that RF modules are less efficient at higher baud rates and may experience loss of data. Hence, I had to replace the RF module with the HC-12 module. Here is a reference: https://www.engineersgarage.com/arduino/rf-module-with-arduino-and-89c51-microcontroller/
