### ISSUE TITLE
PCB Design

### ISSUE THREAD

**Issue by mikeshams** [gurman1995/capstone-project-embt-2020#8]
Abdul - 1) what issues did you face when PCB Design? 2) what is the difference between a zero PCB and a finished PCB?

**Comment by muqeeth54** [comment]
1. There were no footprints to the components I used from the library in my schematic design. So I had to edit the schematic by selecting the components with the footprints to Design my PCB.

2. Zero PCB is a square or rectangular copper board with holes in it.  We can place the component and solder to create the circuit traces. On the other hand, Finished PCB is like a printed board. The traces are already laid down as per the requirement. It comes with multiples layers and different shapes.
